#!/bin/bash
# CARA STOP & START BOT HARU CHECKER v3.0

echo "=================================================="
echo "🛑 CARA STOP BOT"
echo "=================================================="
echo ""
echo "CARA 1: Stop dari Telegram (Owner only):"
echo "  • Buka bot di Telegram"
echo "  • Kirim: /stopbot"
echo "  • Bot akan stop dalam 2 detik"
echo ""
echo "CARA 2: Stop dari terminal (manual):"
echo "  kill \$(cat bot.pid)"
echo ""
echo "CARA 3: Force kill semua process bot:"
echo "  pkill -9 -f 'python.*bot.py'"
echo ""
echo "=================================================="
echo "🚀 CARA START BOT"
echo "=================================================="
echo ""
echo "python3 bot.py 2>&1 &"
echo "echo \$! > bot.pid"
echo ""
echo "Cek status:"
echo "  cat bot.pid              # Lihat PID"
echo "  curl localhost:8000      # Cek health"
echo ""
echo "=================================================="
echo "📋 COMMAND BERGUNA"
echo "=================================================="
echo ""
echo "Cek bot running:"
echo "  ps aux | grep 'python.*bot.py' | grep -v grep"
echo ""
echo "Lihat log realtime:"
echo "  tail -f bot.log"
echo ""
echo "Stop + Start ulang (restart):"
echo "  kill \$(cat bot.pid) && sleep 2 && python3 bot.py 2>&1 &"
echo "  echo \$! > bot.pid"
echo ""
echo "=================================================="
