#!/bin/bash
# 
# PANDUAN PUSH KE GITHUB - HARU CHECKER BOT
# ==========================================

echo "📦 CARA PUSH PROJECT KE GITHUB"
echo "=============================="
echo ""

echo "1️⃣  BUAT REPO BARU DI GITHUB"
echo "   - Buka: https://github.com/new"
echo "   - Nama repo: haru-checker (atau nama lain)"
echo "   - Description: Netflix Cookie Checker Bot"
echo "   - Public atau Private (pilih sesuai kebutuhan)"
echo "   - ❌ JANGAN centang 'Initialize with README' (sudah ada di project)"
echo "   - Klik 'Create repository'"
echo ""

echo "2️⃣  COPY TOKEN GITHUB (Kalau belum punya)"
echo "   - Buka: https://github.com/settings/tokens"
echo "   - Generate new token (classic)"
echo "   - Centang: 'repo' (Full control of private repositories)"
echo "   - Generate token → COPY token-nya"
echo ""

echo "3️⃣  PUSH KE GITHUB (Jalankan di terminal ini)"
echo ""
echo "   Ganti USERNAME dan REPO_NAME dengan milik kamu:"
echo ""
echo "   git remote add origin https://github.com/USERNAME/REPO_NAME.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "   Kalau diminta password, paste TOKEN yang tadi di-copy (bukan password GitHub!)"
echo ""

echo "4️⃣  UNTUK UPDATE KODE SELANJUTNYA"
echo ""
echo "   # Kalau ada perubahan kode baru:"
echo "   git add -A"
echo "   git commit -m \"Update: deskripsi perubahan\""
echo "   git push"
echo ""

echo "5️⃣  CLONE DI TERMUX (Setelah push berhasil)"
echo ""
echo "   # Di Termux, jalankan:"
echo "   cd ~"
echo "   git clone https://github.com/USERNAME/REPO_NAME.git"
echo "   cd REPO_NAME"
echo "   pip install -r requirements.txt"
echo "   cp .env.example .env"
echo "   nano .env  # Isi BOT_TOKEN"
echo "   python bot.py"
echo ""

echo "✅ SELESAI - Repo siap di-push!"
echo ""
echo "═══════════════════════════════════════════════════════"
echo "💡 TIPS:"
echo "   - Token GitHub rahasia, jangan share ke orang lain"
echo "   - Kalau repo private, clone butuh token juga"
echo "   - File .env otomatis diabaikan (tidak ke-push ke GitHub)"
echo "═══════════════════════════════════════════════════════"
