import re
from datetime import datetime

def flag(country):
    if not country or len(country)!=2:
        return ""
    try:
        return "".join(chr(127397+ord(c.upper())) for c in country)
    except:
        return ""

def format_account_block(idx, cookie_dict, info, nftoken, header_cookie):
    # info fields
    email = info.get("email") or "UNKNOWN"
    country = info.get("countryOfSignup") or "UNKNOWN"
    plan = info.get("localizedPlanName") or "Unknown"
    member_since = info.get("memberSince") or "-"
    next_billing = info.get("nextBillingDate") or "-"
    payment = info.get("paymentMethodType") or "N/A"
    owner = info.get("accountOwnerName") or email.split("@")[0]
    phone = info.get("phoneNumber") or "N/A"
    # Try to prettify dates
    try:
        # memberSince may be like 2026-07-07
        dt=datetime.fromisoformat(member_since.replace("Z",""))
        member_since=dt.strftime("%d %b %Y")
    except:
        pass
    country_flag=flag(country) if len(country)==2 else ""
    region=f"{country} {country_flag}".strip()
    # build cookie string
    cookie_str = "; ".join([f"{k}={v}" for k,v in cookie_dict.items()])
    # nftoken links
    pc_link=""
    mobile_link=""
    if nftoken and nftoken.get("token"):
        tok=nftoken["token"]
        pc_link=f"https://www.netflix.com/nftoken={tok}"
        # alternative format used in valid_accounts.txt: /account?nftoken=
        pc_link2=f"https://www.netflix.com/account?nftoken={tok}"
        pc_link=pc_link2  # use account link like in file
        mobile_link=f"https://www.netflix.com/unsupported?nftoken={tok}"
    block=[]
    block.append(f"{email}")
    block.append("")
    block.append("--- NETFLIX ACCOUNT ---")
    block.append("")
    status="Active" if info.get("membershipStatus","").lower().find("current")!=-1 else info.get("membershipStatus") or "Active"
    block.append(f"• Status: {status}")
    block.append(f"• Region: {region}")
    block.append(f"• Member Since: {member_since}")
    block.append(f"• Owner: {owner}")
    block.append(f"• Plan: {plan}")
    block.append(f"• Payment: {payment}")
    block.append(f"• Next Billing: {next_billing}")
    profiles=info.get("profiles") or owner
    block.append(f"• Profiles: {profiles}")
    block.append(f"• Email: {email}")
    block.append(f"  Not Verified")
    block.append(f"• Phone: {phone}")
    block.append(f"  Not Verified")
    extra=info.get("showExtraMemberSection")
    if extra:
        block.append(f"• Extra Members: {extra}")
    lang=info.get("displayLanguage") or "English"
    # block.append(f"• Display Language: {lang}")
    block.append("")
    if pc_link:
        block.append("CLICK HERE TO LOGIN")
        block.append(pc_link)
        if mobile_link:
            block.append(mobile_link)
        block.append("")
    block.append("• Cookie:")
    block.append(f"`{cookie_str}`" if False else cookie_str)
    block.append("")
    block.append("─"*30)
    return "\n".join(block)

def format_summary(total, valid, hold, invalid, speed, elapsed):
    lines=[]
    lines.append(f"Total: {total}")
    lines.append(f"Valid: {valid}")
    lines.append(f"Hold: {hold}")
    lines.append(f"Invalid: {invalid}")
    lines.append(f"Speed: {speed:.1f} cookies/sec")
    lines.append(f"Time: {elapsed:.1f}s")
    return "\n".join(lines)

def summary_for_zip(total, valid, hold, invalid):
    # for _SUMMARY.txt
    lines=[]
    lines.append(f"Total: {total}")
    lines.append(f"Valid: {valid}")
    lines.append(f"Hold: {hold}")
    lines.append(f"Invalid: {invalid}")
    lines.append("")
    lines.append("Generated by Netflix Cookie Converter")
    return "\n".join(lines)
