name: Auto Renew FPS.ms

on:
  schedule:
    - cron: "0 */8 * * *" # tiap 8 jam (00:00, 08:00, 16:00 UTC)
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - run: python scripts/renew_fps.py
        env:
          FPS_API_KEY: ${{ secrets.FPS_API_KEY }}
